# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: CI Pipeline

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [20.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - name: Install dependencies
      run: npm install

    - name: Start server
      run: |
        nohup npm start &
        sleep 30 # Asegura que el servidor tenga tiempo de iniciarse

    - name: Run tests
      run: npm run cypress:run

    - name: Stop server
      run: |
        fuser -k 3000/tcp # Finaliza el servidor despues de ejecutarse

    - name: Login Dockerhub
      env:
        DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      run: docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD

    - name: Build the Docker image
      run: docker build -t ${{ secrets.DOCKER_USERNAME }}/cicd-pipeline:latest . 
    
    - name: Push to Dockerhub
      run: docker push ${{ secrets.DOCKER_USERNAME }}/cicd-pipeline:latest
